language: node_js
cache: yarn
node_js:
- '6'
- '7'
- node
before_script: npm run lint
deploy:
  on:
    tags: true
    branch: master
  provider: npm
  email:
    secure: o/494GNikIU2RtD0yphBHX0z+JMMF6QemuQUChNoV00Iv0Ht/qS5VeEadOST87jl0urEpoYvYLQKAjvYke8aNzrrxBz+xn10hZNO6kkPUtnvnAJf67h9r9rZh7MNry/Ox41rat7MIKq8Z9AhDpLSQSTW2V07uUvJ8/SQczU6l3SmSbbS+X13BYaJhvgnQmfQk/7760PTls7PwgFm2ID1mBRtFSlz6+rFhtRHQnzFPv2etpmG2C7yA8eAmigAlwrAnwwn1kre8akpTcM9YYgWdzUsVOyPS6UUUbYXhholrksjCNQhMpiobXnvPOjQIL/iR97hgOHhFMSLJHgN1nAQFj0I1LJde8HWegjgTteBkNrO1RU7nFIS4+85A3faIMdqza7Bv7ZSfdZXc/jbbgQnjai2NNZgQrEdDYYM9LZh61gS0ryej/ZWJKgxJUGHAzQqgxMoLwvKJ6Th3Q2Bfqucfc8bjzAkFTjNniUSjsjkU/Z8t7maIBE+D2F9nVVHkArmfFt5/fcbWriqTJW2DKLPR68jmjuQnurvBLTIRUJzNBB579Om2/P1+e6UVP1DDYgWIgiFiuXo0xXdl/gohTO0MdfSJGu+wWah9YvkgN9De3awEbN/4fG7WM2/yksI/g/kpyoFtHl7WJzlzuEuM8pXx5cv5hE3f31vOiCqizKunEI=
  api_key:
    secure: uYcY0OLFcN7zRgHSqRSz0rIpUSG4e2/mXwkIFRHY/yseA2sbMEVFrrZR4KRUNHY2LCh9Abhy6ycgs+BNK6iqIP2qQxaIFpFtPlSKv0BB+KCOBnFFqv5fsnO98v+pvfnTqJl2w2WOXOTqDeKfXJ5PlDP7/amXQsDnEZvf8RyiqXjj7F75+O3Z4F62K94DYIfOIkLKeo3mqRizbbXI+JJTOSAIXi8n6p/vuWA9UUf5DjhSskWyF0FklI5unoQiyTUunfsWA6BGvyA5JS/9cLYuBdRagi/8LGvnUi8afE6RXPM7GV1Ic7LiYX2RChzp7lTfiHFyzLi4rkFyz7LRCMqlolLJePdaCkrvO8XU0lemwUPFYBqDOW3UxeljIq41MwcW//wxpI/ieEeTUsTSQfJuRqSxZPxQ9Nn9GcuXr78nILpYbDThUicpFnqlM31GULOC8nL9jI0p0gc5J8zdcuj7kKssJeInudBfEiOdRzPA3Lg/2rBAfEtQIvrUhYy74AbVAKqIYk73umsK/56ZEwdDynTie38VFm2895NglDTJ8+bKGr2TMuwqry4ibHUGORaguBEXqbaUwtBVYNUyiAKilO93OKD0mtJQT/evPRKObXSP0ciTat8kgF5jA3oL9xnzKf8opATvnUauJnKAlZ9D37iVJOTOezGmxPsryQKqxAY=
