language: node_js
cache: yarn
node_js:
- '6'
- node
before_script: npm run lint
deploy:
  on:
    tags: true
    branch: master
  provider: npm
  email: hanifbbz@gmail.com
  api_key:
    secure: uYcY0OLFcN7zRgHSqRSz0rIpUSG4e2/mXwkIFRHY/yseA2sbMEVFrrZR4KRUNHY2LCh9Abhy6ycgs+BNK6iqIP2qQxaIFpFtPlSKv0BB+KCOBnFFqv5fsnO98v+pvfnTqJl2w2WOXOTqDeKfXJ5PlDP7/amXQsDnEZvf8RyiqXjj7F75+O3Z4F62K94DYIfOIkLKeo3mqRizbbXI+JJTOSAIXi8n6p/vuWA9UUf5DjhSskWyF0FklI5unoQiyTUunfsWA6BGvyA5JS/9cLYuBdRagi/8LGvnUi8afE6RXPM7GV1Ic7LiYX2RChzp7lTfiHFyzLi4rkFyz7LRCMqlolLJePdaCkrvO8XU0lemwUPFYBqDOW3UxeljIq41MwcW//wxpI/ieEeTUsTSQfJuRqSxZPxQ9Nn9GcuXr78nILpYbDThUicpFnqlM31GULOC8nL9jI0p0gc5J8zdcuj7kKssJeInudBfEiOdRzPA3Lg/2rBAfEtQIvrUhYy74AbVAKqIYk73umsK/56ZEwdDynTie38VFm2895NglDTJ8+bKGr2TMuwqry4ibHUGORaguBEXqbaUwtBVYNUyiAKilO93OKD0mtJQT/evPRKObXSP0ciTat8kgF5jA3oL9xnzKf8opATvnUauJnKAlZ9D37iVJOTOezGmxPsryQKqxAY=
